name: Deploy to Hosting via FTP with Incremental Updates

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload to FTP with Incremental Updates
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.FTP_HOST }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          remoteDir: ${{ secrets.FTP_DIRECTORY }}
          localDir: "./"
          # Không dùng --delete để tránh xóa file không có trong repo
          # Chỉ upload file mới hoặc đã sửa