name: Deploy to Hosting via Git-FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Cần lịch sử Git đầy đủ để so sánh

      - name: Install git-ftp
        run: sudo apt-get update && sudo apt-get install -y git-ftp

      - name: Deploy with git-ftp
        env:
          GIT_FTP_URL: ftp://${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }}@${{ secrets.FTP_HOST }}:21${{ secrets.FTP_DIRECTORY }}
        run: |
          echo "Deploying to $GIT_FTP_URL"
          # Khởi tạo lần đầu nếu chưa deploy
          git ftp init || true
          # Đẩy các thay đổi
          git ftp push