name: Deploy to Hosting via Git-FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Cần lịch sử Git đầy đủ để so sánh

      - name: Install git-ftp
        run: |
          sudo apt-get update
          sudo apt-get install -y git-ftp
          git-ftp --version # Kiểm tra phiên bản

      - name: Deploy with git-ftp
        run: |
          # Khởi tạo lần đầu nếu chưa deploy
          git ftp init --user "wezqiceb" --passwd "HgYuYxCT6F" -n "103.97.126.29" --remote-root "/domains/phuthobooking.online/public_html/" || true
          # Đẩy các thay đổi
          git ftp push --user "wezqiceb" --passwd "HgYuYxCT6F" -n "103.97.126.29" --remote-root "/domains/phuthobooking.online/public_html/"