name: Deploy to Hosting via Git-FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Cần lịch sử Git đầy đủ để so sánh

      - name: Install git-ftp
        run: |
          sudo apt-get update
          sudo apt-get install -y git-ftp
          git-ftp --version # Kiểm tra phiên bản

      - name: Deploy with git-ftp
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          FTP_DIRECTORY: ${{ secrets.FTP_DIRECTORY }}
        run: |
          # Khởi tạo lần đầu nếu chưa deploy
          git ftp init --user "$FTP_USERNAME" --passwd "$FTP_PASSWORD" -n "$FTP_HOST" --remote-root "$FTP_DIRECTORY" || true
          # Đẩy các thay đổi
          git ftp push --user "$FTP_USERNAME" --passwd "$FTP_PASSWORD" -n "$FTP_HOST" --remote-root "$FTP_DIRECTORY"